config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tags/:tag', to: 'articles#index', as: :tag
  resources :articles do
    member do
      put "like", to: "articles#upvote"
    end
    resources :comments do
      member do
        get "like", to: "comments#upvote"
        get "dislike", to: "comments#downvote"
      end
    end
  end
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  is_impressionable
  include PgSearch
  pg_search_scope :search, against: [:title, :body], :using => {
                    :tsearch => {:prefix => true}
                  }
  acts_as_taggable
  acts_as_votable
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true, length: { minimum: 10}
  has_many :comments, dependent: :destroy
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validate :picture_size

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name, presence: true
  validates :body, presence: true, length: { minimum: 10}
  acts_as_votable
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 after_filter :store_location

 def store_location
   # store last url - this is needed for post-login redirect to whatever the user last visited.
   return unless request.get?
   if (request.path != "/users/sign_in" &&
       request.path != "/users/sign_up" &&
       request.path != "/users/password/new" &&
       request.path != "/users/password/edit" &&
       request.path != "/users/confirmation" &&
       request.path != "/users/sign_out" &&
       !request.xhr?) # don't store ajax calls
     session[:previous_url] = request.fullpath
   end
 end

 def after_sign_in_path_for(resource)
   session[:previous_url] || root_path
 end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show, :upvote]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :login_like, only: [:upvote]
  impressionist actions: [:show]

  # GET /articles
  # GET /articles.json
  def index
    if params[:search].present?
      @articles = Article.search(params[:search]).order('created_at DESC').paginate(page: params[:page], per_page: 3)
      if params[:tag]
        @articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 3)
      end
    else
      @articles = Article.all.order('created_at DESC').paginate(page: params[:page], per_page: 3)
      if params[:tag]
        @articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 3)
      end
    end
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        flash[:success] = 'Article was successfully created.'
        format.html { redirect_to @article}
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        flash[:success] = 'Article was successfully updated.'
        format.html { redirect_to @article }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully destroyed.'
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  def upvote
    @article.upvote_from current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :tag_list, :picture)
    end

    def require_same_user
      if current_user.id != @article.user_id && current_user.admin != true
        flash[:danger] = "You can only edit or delete your own articles!"
        redirect_to(root_path)
      end
    end

    def login_like
      if !user_signed_in?
        flash[:danger] = "You must log in to like this article!"
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :set_comment, except: [:create]
  before_action :login_like, only:[:upvote, :downvote]
  def create
    @comment = @article.comments.create(params[:comment].permit(:name, :body))
    if @comment.save
      respond_to do |format|
        format.html { redirect_to(@article) }
        format.js # render 'create.js.erb'
      end
    end
  end

  def destroy
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to(article_path(@article)) }
        format.js
      end
    end
  end

  def upvote
    if @comment.upvote_from current_user
      respond_to do |format|
        format.html { redirect_to(:back) }
        format.js
      end
    end
  end

  def downvote
    if @comment.downvote_from current_user
      respond_to do |format|
        format.html { redirect_to(:back) }
        format.js
      end
    end
  end

  private

    def set_article
      @article = Article.find(params[:article_id])
    end

    def set_comment
      @comment = @article.comments.find(params[:id])
    end

    def login_like
      if !user_signed_in?
        flash[:danger] = "You must log in to like or dislike comments!"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/articles/_article.html.erb
<div class="text-sm-center">
  <%= will_paginate @articles %>
</div>
<div class="row clearfix">
  <div class="col-sm-8 col-sm-offset-2">
    <% @articles.each do |article| %>
      <div class="card glassy">
        <div class="card-block clearfix">
          <h4 class="card-title article-title"><%= link_to article.title, article %>
            <span class="like text-sm-right">
              <%= link_to like_article_path(article), method: :put do %>
                <span class="fa fa-heart"> <%= article.get_upvotes.size %></span>
              <% end %>
            </span>
          </h4>

          <small class="text-muted"><%= article.created_at.strftime("%B, %d, %Y")  %></small>
          <p class="card-text article-body">
            <% if article.picture? %>
                <%= image_tag(article.picture.url, size: "350x250", class: "img-fluid img-circle center-block picture-index") %>
            <% end %>
            <%= @markdown.render(article.body).html_safe %>
          </p>
        </div>

        <p class="tag">
          Tags: <%= raw article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
        </p>

        <p>
          <span class="fa fa-eye index-view-page text-muted"> <%= article.impressionist_count(:filter=>:session_hash) %>
          </span>
        </p>

        <div class="article-actions text-sm-right clearfix">
          <small class="time-submit text-muted">Submitted <%= time_ago_in_words(article.created_at) %> ago, by <%= article.user.email %></small>
            </div>
      </div>
      <br>
    <% end %>
  </div>

  <div class="tag_cloud pull-sm-right col-sm-2 hidden-sm-down">
    <% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
</div>

<div class="text-sm-center">
  <%= will_paginate %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-sm-12">
    <%= simple_form_for(@article, :html => { class: "form-horizontal", role: "form", multipart: true }) do |f| %>
      <div class="form-group row">
        <div class="form-control-label col-sm-3">
          <%= f.label :title %>
        </div>
        <div class="col-sm-9">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article...", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <div class="form-control-label col-sm-3">
          <%= f.label :tag_list, "Tags (separated by commas)" %>
        </div>
        <div class="col-sm-9">
          <%= f.text_field :tag_list, class: "form-control", placeholder: "Tags, tags, tag..." %>
        </div>
      </div>

      <div class="form-group row">
        <div class="form-control-label col-sm-3">
          <%= f.label :body %>
        </div>
        <div class="col-sm-9">
          <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Content of the article..." %>
        </div>
      </div>

      <div class="form-group row">
        <div class="form-control-label col-sm-3">
          <%= f.label :picture %>
        </div>
        <div class="col-sm-9">
          <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-9">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <div class="col-sm-5 col-sm-offset-5">
      [ <%= link_to "Cancel request and return to articles listing", articles_url %> ]
    </div>
  </div>
</div>

<script type="text/javascript">
$('#article_picture').bind('change', function() {
  size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 5) {
    alert('Maximum file size is 5MB. Please choose a smaller file');
  }
});
</script>

app/views/articles/edit.html.erb
<h1 align="center">Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 align="center" class="body-padding">My First Rails Application for CoderSchool</h1>

<%= render 'article' %>

<br>

app/views/articles/new.html.erb
<h1 class="new-form" align="center">New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row clearfix">
<div class="card  col-sm-8 col-sm-offset-2 glassy">
  <div class="card-block">
  <h2 class="title-show text-sm-center card-title">
    <%= @article.title %>
  </h2>
    <div class="card-text content-show clearfix">
      <% if @article.picture? %>
          <%= image_tag(@article.picture.url, size: "350x250", class: "img-fluid center-block picture img-circle") %>
      <% end %>
      <%= simple_format(@article.body) %>
      <p class="tag-show">
        Tags: <%= raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </p>
      <span class="fa fa-eye view-page text-muted">        <%= @article.impressionist_count(:filter=>:session_hash) %>
      </span>
      <span class="like-show text-sm-right">
        <%= link_to like_article_path(@article), method: :put do %>
          <span class="fa fa-heart"> <%= @article.get_upvotes.size %></span>
        <% end %>
      </span>
    </div>


    <div class="article-actions text-sm-right clearfix">
      <small class="time-submit-show text-muted">Submitted <%= time_ago_in_words(@article.created_at) %> ago, by <%= @article.user.email %></small>
      <% if (user_signed_in? && @article.user_id == current_user.id) || (user_signed_in? && current_user.admin == true)  %>
        <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-sm btn-primary" %>
        <%= link_to 'Delete', article_url(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-sm btn-danger" %>
      <% end %>
    </div>
</div>
</div>


  <div class="tag_cloud pull-sm-right col-sm-2 hidden-sm-down">
    <% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>

<div class="card col-sm-8 col-sm-offset-2 comments-section glassy-comment">
    <h2 style="padding-top: 7px;">                   Comment </h2>
  <hr>
  <div id="comments">
    <%= render @article.comments %>
  </div>
  <h3>Add a comment:</h3>
  <div class="comment-wrapper">
    <%= render 'comments/form' %>
  </div>
</div>
</div>

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
  <p class="comment-title">
    <strong><%= comment.name %></strong>
  </p>
  <p class="comment-content">
    <%= word_wrap(comment.body) %>
  </p>
  <small class="text-muted">
    <%= time_ago_in_words(comment.created_at) %> ago
  </small>
  <p class="comment-reputation clearfix">
    <span class="like-comment">
      <%= link_to like_article_comment_url(@article, comment), method: :get, remote: true do %>
        <span class="fa fa-thumbs-up" id="thumbs-up"> <%= comment.get_upvotes.size %></span>
      <% end %>
    </span>
    <p class="dislike-comment">
      <%= link_to dislike_article_comment_url(@article, comment), method: :get, remote: true do %>
        <span class="fa fa-thumbs-down" id="thumbs-down"> <%= comment.get_downvotes.size %></span>
      <% end %>
    </p>
  </p>

  <p class="text-sm-left">
    <% if (user_signed_in? && current_user.id == @article.user_id) || (user_signed_in? && current_user.admin == true) %>
      <%= link_to 'Delete', [comment.article, comment], method: :delete, class: "btn btn-secondary btn-sm", data: { confirm: "Are you sure you want to delete this comment?" }, remote: true %>
    <% end %>
  </p>
  <hr>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@article, @article.comments.build], remote: true) do |f| %>

  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :name, class: "form-control-label" %>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control", placeholder: "Anyname..." %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :body, class: "form-control-label" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Write a comment..." %>
    </div>
  </div >
  <br>
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>").hide().fadeIn('slow');

// Empty the form
$('#comment_name').val("");
$('#comment_body').val("");

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').fadeOut('slow', function () {
   $(this).remove();
});

app/views/comments/downvote.js.erb
$('#thumbs-down').replaceWith("<%= j render comment.get_downvotes.size %>");

app/views/comments/upvote.js.erb
$('#thumbs-up').replaceWith("<%= j render comment.get_upvotes.size %>");

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded exciting-navbar">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
   &#9776;
  </button>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <%= link_to 'Simple Blog', root_url, class: 'navbar-brand' %>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to root_url, class: "nav-link" do%>
          <i class="fa fa-home"></i>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to image_tag(avatar_url(current_user), class: "img-circle profile-image"), edit_user_registration_path, class: "nav-link" %>
        </li>
        <% if (user_signed_in? && current_user.admin == true) %>
          <li class="nav-item admin">
            Admin
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <i class="fa fa-user-plus"></i>
          <% end %>
        </li>
      <% end %>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fa fa-user"></i>
          <% end %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New Article", new_article_path, class: "nav-link" %>
      </li>
    </ul>
    <%= form_tag(articles_path,  :id => 'custom-search-input', method: :get, class: "navbar-form navbar-custom-form pull-sm-right", role: "search") do  %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search title or content..." %>
        <span class="input-group-btn">
          <%= button_tag(:class => "btn btn-secondary") do %>
            <span class="fa fa-search"></span>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogCodeSchool</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Nunito:400,700,300' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-sm-9 col-sm-offset-3">
      <div class="card">
        <div class="card-header card-inverse card-danger">
          <div class="card-title">
            <%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:
            </div>
            <div class="card-text">
              <ul>
                <% obj.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>